title = 'Artur Rios'
theme = 'rusty-typewriter'
themesdir = 'themes'
enableRobotsTXT = true

[params]
enableComments=true
giscusTheme="preferred_color_scheme"

# rtwt = Rusty Typewriter Theme
[params.rtwt.home]
showAuthorImg = false

[params.rtwt.side.home]
taxonomies = ['tags','series']
countTaxonomy = 3

[taxonomies]
tag = 'tags'
topic = 'topics'
series = 'series'

[params.author]
name = 'Artur Rios'

defaultContentLanguage = "en"
[languages]
  [languages.en]
    contentDir = 'content/english'
    languageCode = 'en-US'
    languageName = 'English'
    weight = 10

    [[languages.en.menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 1

    [[languages.en.menus.main]]
    name = 'About'
    pageRef = '/about.md'
    weight = 2

    [[languages.en.menus.main]]
    name = 'GitHub'
    url = 'https://github.com/artur-rios'
    weight = 3

    [[languages.en.menus.main]]
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/artur-rios'
    weight = 4

  [languages.pt]
    contentDir = 'content/portuguese'
    languageCode = 'pt-BR'
    languageName = 'PortuguÃªs'
    weight = 20

    [[languages.pt.menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 1

    [[languages.pt.menus.main]]
    name = 'Sobre'
    pageRef = '/about.md'
    weight = 2

    [[languages.pt.menus.main]]
    name = 'GitHub'
    url = 'https://github.com/artur-rios'
    weight = 3

    [[languages.pt.menus.main]]
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/artur-rios'
    weight = 4

# build search index ================
[outputFormats]
 [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[mediaTypes]
 [mediaTypes."application/json"]
  suffixes = ["json"]

[outputs]
 home = ["HTML","RSS", "SearchIndex"]
# ===================================
